server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index landing_page.html;

    location / {
        try_files $uri $uri/ /landing_page.html;
    }

    location ~* \.(avif|svg|ico|woff2?)$ {
        expires 7d;
        add_header Cache-Control "public";
    }
}
